name: "build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GODOT_VERSION: 3.5
  EXPORT_NAME: Lorien
  LORIEN_VERSION: v0.6.0-dev
  GDCLIP_VERSION: v0.2

jobs:
  windows-export:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          mkdir -v -p build/${EXPORT_NAME}_${LORIEN_VERSION}_Windows
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          mkdir -p lorien/InfiniteCanvas/GDClip/bin
          cd lorien/InfiniteCanvas/GDClip/bin
          wget https://github.com/hansemro/GDClip/releases/download/${GDCLIP_VERSION}/libgdclip-windows-x86_64-release.zip
          unzip libgdclip-windows-x86_64-release.zip
      - name: Windows Build
        run: | 
          cd lorien
          godot -v --export "Windows Desktop" ../build/${EXPORT_NAME}_${LORIEN_VERSION}_Windows/${EXPORT_NAME}_${LORIEN_VERSION}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Lorien Windows
          path: build/${{ env.EXPORT_NAME }}_${{ env.LORIEN_VERSION }}_Windows
          retention-days: 14

  linux-export:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          mkdir -v -p build/${EXPORT_NAME}_${LORIEN_VERSION}_Linux
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          mkdir -p lorien/InfiniteCanvas/GDClip/bin
          cd lorien/InfiniteCanvas/GDClip/bin
          wget https://github.com/hansemro/GDClip/releases/download/${GDCLIP_VERSION}/libgdclip-linux-x86_64-release.zip
          unzip libgdclip-linux-x86_64-release.zip
      - name: Linux Build
        run: | 
          cd lorien
          godot -v --export "Linux/X11" ../build/${EXPORT_NAME}_${LORIEN_VERSION}_Linux/${EXPORT_NAME}_${LORIEN_VERSION}.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Lorien Linux
          path: build/${{ env.EXPORT_NAME }}_${{ env.LORIEN_VERSION }}_Linux
          retention-days: 14

  mac-export:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          mkdir -v -p build/${EXPORT_NAME}_${LORIEN_VERSION}_Mac
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          mkdir -p lorien/InfiniteCanvas/GDClip/bin
          cd lorien/InfiniteCanvas/GDClip/bin
          wget https://github.com/hansemro/GDClip/releases/download/${GDCLIP_VERSION}/libgdclip-macos-x86_64-release.zip
          unzip libgdclip-macos-x86_64-release.zip
      - name: Mac Build
        run: | 
          cd lorien
          godot -v --export "Mac OSX" ../build/${EXPORT_NAME}_${LORIEN_VERSION}_Mac/${EXPORT_NAME}_${LORIEN_VERSION}.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Lorien Mac
          path: build/${{ env.EXPORT_NAME }}_${{ env.LORIEN_VERSION }}_Mac
          retention-days: 14
